liveupdate/urls.py
from django.urls import path, re_path

from . import views

app_name = 'liveupdate'
urlpatterns = [
    re_path(r'^$', views.relation_list, name='event_list'),
    re_path(r'^live/(?P<event_id>\d+)/$', views.update_event_list, name='event_live_id'),
    re_path(r'^updates-after/(?P<update_id>\d+)/$', views.update_after),
    path('<int:year>/<int:month>/', views.EventMonthArchiveView.as_view(month_format='%m'), name='event_archive_month'),
]

sport_news/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news_portal.urls', namespace='news_portal')), 
    path('contact/', include('leave_message.urls')),
    path('liveupdate/', include('liveupdate.urls', namespace='liveupdate')),
    
    re_path(r'^photologue/', include(('photologue_custom.urls', 'photologue_custom'), namespace='photologue_custom')),
    re_path(r'^photologue/', include('photologue.urls', namespace='photologue')),
    re_path(r'^polls/', include(('poll.urls', 'poll'), namespace='poll')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

liveupdate/models.py
from django.db import models
from django.contrib import admin
from django.urls import reverse

from django.utils import timezone

from datetime import date, datetime


# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=250)
    is_published = models.BooleanField(default=True)
    start_time = models.DateTimeField(default=timezone.now)
    is_ended = models.BooleanField(default=False)

    class Meta:
        ordering = ['is_ended', '-start_time', '-id']

    def __str__(self):
        return self.name

    objects = models.Manager()
    

class Entry(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    event_id = models.ForeignKey(
        Event, on_delete = models.CASCADE
    )
    text = models.TextField()

    class Meta:
        ordering = ['-id']
        verbose_name_plural = "Entries"

    def __str__(self):
        timest = timezone.localtime(self.timestamp)
        string = timest.strftime("%Y-%m-%d %H:%M:%S") + " " + self.text
        return string

    objects = models.Manager()

liveupdate/views.py
from django.http import HttpResponse
from django.core import serializers
from django.core.paginator import EmptyPage, InvalidPage, Paginator
from django.shortcuts import render
from django.views.generic.dates import MonthArchiveView

from .models import Event, Entry

from news_portal.utilities import get_layout_dict, render_with_db_extra_context

# Create your views here.
def relation_list(request):
    records = Event.objects.select_related().filter(is_published = True)

    paginator = Paginator(records, 10)

    page = request.GET.get('page')
    try:
        events = paginator.page(page)
    except (EmptyPage, InvalidPage):
        events = paginator.page(1)


    return render_with_db_extra_context(request, 'liveupdate/relation_list.html', {
        'object_list': events
        })

def update_event_list(request, event_id):
    records = Entry.objects.select_related().filter(event_id = event_id)
    events = Event.objects.select_related().filter(pk = event_id, is_published = True)
    if (events):
        event = events[0]
        return render_with_db_extra_context(request, 'liveupdate/update_list.html', {
            'object_list': records,
            'event_name': event.name,
            'event_id': event.pk,
            'event_ended': '[ended]' if (event.is_ended) else '',
            })
    return HttpResponse(status=404)

def update_after(request, update_id):
    response = HttpResponse()
    response['Content-Type'] = "text/javascript"
    response.write(
        serializers.serialize(
            "json", Entry.objects.select_related().filter(pk__gt = update_id)
            )
        )

    return response

class EventMonthArchiveView(MonthArchiveView):
    queryset = Event.objects.select_related().filter(is_published = True, is_ended = False)
    date_field = 'start_time'
    allow_future = True
    extra_context = get_layout_dict()

liveupdate/templates/liveupdate/event_archive_month.html
{% extends "base.html" %}

{% block content %}
<div>
<ul>
    {% for event in object_list %}
    <h3>
    <li>{{event.start_time|date:"F j, Y"}}: <a href="{% url 'liveupdate:event_live_id' event.pk %}">{{event.name}}</a></li>
    </h3>
    {% endfor %}
</ul>
</div>
{% endblock %}

liveupdate/templates/liveupdate/relation_list.html
{% extends "base.html" %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}

        {% if object_list %}
        <div id="update-holder">
                {% for object in object_list %}
                    <h2>
                        <a href="{% url 'liveupdate:event_live_id' object.pk %}">{{ object.name }}</a>
                    </h2>
                    {{object.start_time}}
                    {% if object.is_ended %}
                    (ended)
                    {% else %}
                    (ongoing)
                    {% endif %}
                {% endfor %}
        </div>
        {% endif %}

        <div class="pagination">
                <span class="step-links">
                    {% if object_list.has_previous %}
                        <a href="?page=1" class="btn btn-primary">First</a>
                        <a href="?page={{ object_list.previous_page_number }}" class="btn btn-secondary">Previous</a>
                    {% endif %}
            
                    <span class="current">
                        (Page {{ object_list.number }}/{{ object_list.paginator.num_pages }})
                    </span>
            
                    {% if object_list.has_next %}
                        <a href="?page={{ object_list.next_page_number }}" class="btn btn-secondary">Next</a>
                        <a href="?page={{ object_list.paginator.num_pages }}" class="btn btn-primary">Last</a>
                        
                    {% endif %}
                </span>
        </div>


{% endblock %}

liveupdate/templates/liveupdate/update_list.html
{% extends "base.html" %} 
{% load static %}

{% block livescripts %}
<link rel="stylesheet" type="text/css" href="{% static 'css/live.css' %}">
<script type="text/javascript" language="javascript" src="{% static 'js/jquery-1.2.3.min.js' %}"></script>
<script type="text/javascript" language="javascript" src="{% static 'js/livescript_update.js' %}" >
</script>
<script>
    $(document).ready(function () {
    setInterval("update( {{event_id}} )", 15000);
})
</script>
{% endblock %}

{% block content %}
    <h1>{{event_name}} {{event_ended}}</h1>
    <p>Please do <b>not</b> refresh! Update every few seconds</p>

    {% if object_list %}
    <div id="update-holder">
        {% for object in object_list %}
        <div class="update {% cycle 'even' 'odd' %}" id="{{ object.id }}">
            <div class="timestamp">
                {{ object.timestamp }}
            </div>
            <div class="text">
                {{ object.text | linebreaksbr }}
            </div>
            <div class="clear"></div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>No entries</p>
    {% endif %} 
{% endblock %}