leave_message/urls.py
from django.contrib import admin
from django.urls import path, re_path

from . import views

app_name = 'leave_message'
urlpatterns = [
    path('email/', views.emailView, name='email'),
    path('success/', views.successView, name='success'),
    path('error/', views.errorView, name='error'),
]

liveupdate/urls.py
from django.urls import path, re_path

from . import views

app_name = 'liveupdate'
urlpatterns = [
    re_path(r'^$', views.relation_list, name='event_list'),
    re_path(r'^live/(?P<event_id>\d+)/$', views.update_event_list, name='event_live_id'),
    re_path(r'^updates-after/(?P<update_id>\d+)/$', views.update_after),
    path('<int:year>/<int:month>/', views.EventMonthArchiveView.as_view(month_format='%m'), name='event_archive_month'),
]

sport_news/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news_portal.urls', namespace='news_portal')), 
    path('contact/', include('leave_message.urls')),
    path('liveupdate/', include('liveupdate.urls', namespace='liveupdate')),
    
    re_path(r'^photologue/', include(('photologue_custom.urls', 'photologue_custom'), namespace='photologue_custom')),
    re_path(r'^photologue/', include('photologue.urls', namespace='photologue')),
    re_path(r'^polls/', include(('poll.urls', 'poll'), namespace='poll')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leave_message/models.py
from django.db import models
from django.utils.timezone import now

from datetime import date, datetime

class Message(models.Model): 
    from_email = models.EmailField()
    subject = models.CharField(max_length=250)
    content = models.CharField(max_length=1000)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ['-timestamp']
        
    def __str__(self):
        timest = datetime.date(self.timestamp)
        string = "[" + timest.strftime("%Y-%m-%d %H:%M:%S") + "] " + self.subject
        return string

leave_message/forms.py
from django import forms

class MessageForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True, max_length=250)
    content = forms.CharField(widget=forms.Textarea, required=True, max_length=1000)

leave_message/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import MessageForm
from .models import Message

from news_portal.utilities import render_with_db_extra_context

# Helpers
def get_form_page(request, form):
    return render_with_db_extra_context(request, 'leave_message/email.html', {
        'form': form,})

def redirect_to_ok_alert_page(request):
    return HttpResponseRedirect(
        reverse('leave_message:success')
        )

def redirect_to_err_alert_page(request):
    return HttpResponseRedirect(
        reverse('leave_message:error')
        )

# Create your views here.
def emailView(request):
    if request.method == 'GET':
        form = MessageForm()
    else:
        form = MessageForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            content = form.cleaned_data['content']
            try:
                send_mail(subject, content, from_email, ['admin@example.com'])
                f = Message(
                    from_email=from_email,
                    subject=subject,
                    content=content)
                f.save()
            except BadHeaderError:
                return redirect_to_err_alert_page(request)
            return redirect_to_ok_alert_page(request)
    return get_form_page(request, form)

def successView(request):
    return render_with_db_extra_context(request, 'leave_message/alert.html', {
        'status': 'ok',
        'alerttext': 'Well done! You successfully sent message.',})\

def errorView(request):
    return render_with_db_extra_context(request, 'leave_message/alert.html', {
        'status': 'error',
        'alerttext': 'Oh no! It is possible that something needs to be improved.',})

leave_message/templates/leave_message/alert.html
{% extends "base.html" %}

{% block content %}

    <h1>Contact Us</h1>

    {% if status == "ok" %}
    <div class="alert alert-success" role="alert">{{alerttext}}</div>
    {% elif status == "error" %}
    <div class="alert alert-danger" role="alert">{{alerttext}}</div>
    {% endif %}
{% endblock %}

leave_message/templates/leave_message/email.html
{% extends "base.html" %}

{% block content %}

    <h1>Contact Us</h1>

    <form method="post">
        {% csrf_token %}  
        <div class="form-group">
            <label for="id_from_email">From email:</label>
            <input type="email" class="form-control" name="from_email" required id="id_from_email" placeholder="Enter email">
        </div>

        <div class="form-group">
            <label for="id_subject">Subject:</label>
            <input type="text" class="form-control" name="subject" required id="id_subject" maxlength="250">
        </div>

        <div class="form-group">
            <label for="id_content">Message content:</label>
            <textarea class="form-control" name="content" cols="40" rows="10" maxlength="1000" required id="id_content"></textarea>
        </div> 

        <div class="form-actions">
        <input type="submit" class="btn btn-primary" />
        </div>
    </form>
{% endblock %}