liveupdate/urls.py
from django.urls import path, re_path

from . import views

app_name = 'liveupdate'
urlpatterns = [
    re_path(r'^$', views.relation_list, name='event_list'),
    re_path(r'^live/(?P<event_id>\d+)/$', views.update_event_list, name='event_live_id'),
    re_path(r'^updates-after/(?P<update_id>\d+)/$', views.update_after),
    path('<int:year>/<int:month>/', views.EventMonthArchiveView.as_view(month_format='%m'), name='event_archive_month'),
]

news_portal/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.urls import include #

from . import views

app_name = 'news_portal'
urlpatterns = [
    path('', views.article_list, name='article_list'),
    re_path(r'^article/(?P<year>\d+)/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[\w-]+)/$', views.article_detail, name='article_detail'),
    path('article/archive/<int:year>/<int:month>/', views.ArticleMonthArchiveView.as_view(month_format='%m'), name='post_archive_month'),
    
    re_path(r'^tag/(?P<slug>[-\w]+)/$', views.TagIndexView.as_view(), name='tagged'),
    re_path("^page/(?P<slug>.*)%s$" % ("/" if settings.APPEND_SLASH else ""), views.static_page, name="static_page"),
]

sport_news/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news_portal.urls', namespace='news_portal')), 
    path('contact/', include('leave_message.urls')),
    path('liveupdate/', include('liveupdate.urls', namespace='liveupdate')),
    
    re_path(r'^photologue/', include(('photologue_custom.urls', 'photologue_custom'), namespace='photologue_custom')),
    re_path(r'^photologue/', include('photologue.urls', namespace='photologue')),
    re_path(r'^polls/', include(('poll.urls', 'poll'), namespace='poll')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sport_news/templates/layout/aside.html
{% block aside %}
<aside class="col-md-4 blog-sidebar">

  <div class="p-3">

    <h4 class="font-italic">Articles - Archives</h4>
    {% regroup all_articles by publish.year as year_list %}
    <ul>
      {% for year in year_list %}
      <li> {{year.grouper}} {% regroup year.list by publish.month as month_list %}
        <ul>
          {% for month in month_list %}
          <li>
            <a href="{% url 'news_portal:post_archive_month' year.grouper month.grouper %}">
              {{ month.list.0.publish|date:'F' }} ({{month.list|length}})
            </a>
          </li>
          {% endfor %}
        </ul>
      </li>
      {% endfor %}
    </ul>

    <h4 class="font-italic">Article - Tags</h4>

    <ul>
      {% for tag in tag_list %}
      <li>
        <a href="{% url 'news_portal:tagged' tag.slug %}">
          {{ tag.name }}
        </a>
      </li>
      {% endfor %}
    </ul>

    <h4 class="font-italic">Ongoing events</h4>
    {% regroup ongoing_live_events by start_time.year as year_list %}
    <ul>
      {% for year in year_list %}
      <li> {{year.grouper}} {% regroup year.list by start_time.month as month_list %}
        <ul>
          {% for month in month_list %}
          <li>
            <a href="{% url 'liveupdate:event_archive_month' year.grouper month.grouper %}">
              {{ month.list.0.start_time|date:'F' }} ({{month.list|length}})
            </a>
          </li>
          {% endfor %}
        </ul>
      </li>
      {% endfor %}
    </ul>
  </div>
  <!--
            <div class="p-3">
              <iframe src="http://www.unogoal.com/free_livescore.aspx" width="100%" height="200"  scrolling="auto" frameborder="0"></iframe><p style="text-align: center;"><a href="http://www.unogoal.com" title="Soccer livescore for blog or website. Get yours now."><img src="http://www.unogoal.com/images/banners/free_livescore_for_website.png" alt="Free livescore from Unogoal.com" title="Free livescore from Unogoal.com" /></a></p> 
            </div>
  -->

</aside>
{% endblock %}

sport_news/templates/layout/footer.html
 {% block footer %}

<footer class="blog-footer" style="background-color: {{footer_bg}}; color: {{footer_txt}};">
  <p>{{label.footer_text}}</p>
  <p>Blog template built for
    <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>
{% endblock %}

sport_news/templates/layout/head.html
{% load static %}
{% block head %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<title>{{label.tab_title}}</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap3/bootstrap.min.css' %}">
<!-- Optional theme -->
<link rel="stylesheet" href="{% static 'css/bootstrap3/bootstrap-theme.min.css' %}">

<link rel="stylesheet" href="{% static 'css/blog.css' %}"> 
{% block script %}{% endblock %}
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet" media="none" onload="if(media!='all')media='all'"> 
{% block livescripts %}{% endblock %} 
{% endblock %}

sport_news/templates/layout/header_nav.html
{% load sitetree %} {% load pagetree_own_tags %} 
{% block header %}
<div class="container" style="background-color: {{header_bg}}; color: {{header_txt}};">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="{% url 'news_portal:article_list' %}">{{label.header_text}}</a>
      </div>
    </div>
  </header>
  {% sitetree_tree from "main" include "trunk,topmenu" template "sitetree/nav_root_menu.html" %}
</div>
{% endblock %}